### ISSUE TITLE
Item click not working

### ISSUE THREAD

**Issue by kardeslik** [orhanobut/simplelistview#3]
If you set item click listener after setting adapter it does not work.

**Comment by akbashev** [comment]
Well wanted to report same issue yesterday, but forgot :)
Confirm that, for proper work you need to set listener after setting the adapter.
Well in my case it worked, but after resuming the fragment didn't, clickListener is null in SimpleListView when refreshList() is called.

**Comment by orhanobut** [comment]
This is fixed
